import { useEffect, useRef, useState } from "preact/hooks";
import { AlertCircle, Check, Loader2 } from "lucide-preact";
import { t, type SupportedLanguage } from "../../../lib/i18n";
import { checkSlugAvailability, cleanSlugInput, generateSlug, isValidSlug } from "../../../lib/slug";

type SlugStatus = "idle" | "valid" | "invalid" | "taken" | "error";

interface Props {
  title: string;
  initialSlug?: string;
  language: string;
  uiLanguage: SupportedLanguage;
  pollId?: string;
  disabled?: boolean;
  onSlugChange: (_slug: string) => void;
  onValidChange?: (_isValid: boolean) => void;
}

export default function SlugInput({
  title,
  initialSlug,
  language,
  uiLanguage,
  pollId,
  disabled = false,
  onSlugChange,
  onValidChange,
}: Props) {
  const [slug, setSlug] = useState(initialSlug ?? "");
  const [slugTouched, setSlugTouched] = useState(Boolean(initialSlug));
  const [isChecking, setIsChecking] = useState(false);
  const [status, setStatus] = useState<SlugStatus>("idle");
  const checkTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    setSlug(initialSlug ?? "");
    setSlugTouched(Boolean(initialSlug));
  }, [initialSlug]);

  useEffect(() => {
    if (!title || slugTouched) return;
    setSlug(generateSlug(title));
  }, [title, slugTouched]);

  useEffect(() => {
    onSlugChange(slug);
  }, [slug, onSlugChange]);

  useEffect(() => {
    if (checkTimeoutRef.current) {
      clearTimeout(checkTimeoutRef.current);
      checkTimeoutRef.current = null;
    }

    if (!slug) {
      setStatus("idle");
      setIsChecking(false);
      onValidChange?.(false);
      return;
    }

    if (!isValidSlug(slug)) {
      setStatus("invalid");
      setIsChecking(false);
      onValidChange?.(false);
      return;
    }

    setIsChecking(true);
    checkTimeoutRef.current = setTimeout(async () => {
      try {
        const available = await checkSlugAvailability(slug, language, pollId);
        setStatus(available ? "valid" : "taken");
        onValidChange?.(available);
      } catch (_err) {
        setStatus("error");
        onValidChange?.(false);
      } finally {
        setIsChecking(false);
      }
    }, 500);

    return () => {
      if (checkTimeoutRef.current) {
        clearTimeout(checkTimeoutRef.current);
        checkTimeoutRef.current = null;
      }
    };
  }, [slug, language, pollId, onValidChange]);

  const handleSlugInput = (value: string) => {
    setSlug(cleanSlugInput(value));
    setSlugTouched(true);
  };

  const statusMessage = (() => {
    if (isChecking) return t(uiLanguage, "polls.slug.checking", "admin");
    if (status === "valid") return t(uiLanguage, "polls.slug.available", "admin");
    if (status === "invalid") return t(uiLanguage, "polls.slug.invalid", "admin");
    if (status === "taken") return t(uiLanguage, "polls.slug.taken", "admin");
    if (status === "error") return t(uiLanguage, "polls.slug.checkFailed", "admin");
    return "";
  })();

  const statusIcon = (() => {
    if (isChecking) return <Loader2 className="h-4 w-4 animate-spin text-blue-500" aria-hidden="true" />;
    if (status === "valid") return <Check className="h-4 w-4 text-green-600" aria-hidden="true" />;
    if (status === "invalid" || status === "taken" || status === "error") {
      return <AlertCircle className="h-4 w-4 text-[var(--color-error)]" aria-hidden="true" />;
    }
    return null;
  })();

  return (
    <div className="slug-input-group">
      {!slugTouched && slug ? (
        <div className="slug-preview">
          <label>{t(uiLanguage, "polls.slug.autoGeneratedWithValue", "admin", { slug })}</label>
          <div className="slug-display">
            <code>{slug}</code>
            <button type="button" className="btn-text" onClick={() => setSlugTouched(true)} disabled={disabled}>
              {t(uiLanguage, "polls.slug.edit", "admin")}
            </button>
          </div>
        </div>
      ) : (
        <div className="slug-edit">
          <label htmlFor="poll-slug" className="text-sm font-semibold">
            {t(uiLanguage, "polls.slug.label", "admin")}
          </label>
          <div className={`slug-input-wrapper ${status}`}>
            <input
              id="poll-slug"
              type="text"
              className="input-field slug-input"
              value={slug}
              placeholder={t(uiLanguage, "polls.slug.placeholder", "admin")}
              minLength={3}
              maxLength={100}
              disabled={disabled}
              onInput={(e) => handleSlugInput((e.currentTarget as HTMLInputElement).value)}
            />
            {statusIcon}
          </div>
          {statusMessage ? <p className={`slug-status ${status}`}>{statusMessage}</p> : null}
          <p className="slug-help">{t(uiLanguage, "polls.slug.help", "admin")}</p>
        </div>
      )}
    </div>
  );
}
